# Generated by Django 5.0.6 on 2024-06-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0005_remove_packagingmouvment_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingmouvment',
            name='packaging',
            field=models.ForeignKey(default='no notes ', on_delete=django.db.models.deletion.CASCADE, related_name='mouvment', to='returnpack.packaging'),
        ),
    ]
